export const INTERNET_ONLINE = 'INTERNET_ONLINE';
export const INTERNET_OFFLINE = 'INTERNET_OFFLINE';

export const WS_CONNECTING = 'WS_CONNECTING';
export const WS_OPENED = 'WS_OPENED';
export const WS_CLOSED = 'WS_CLOSED';

export const PREPARE_MESSAGE_FOR_SENDING = 'PREPARE_MESSAGE_FOR_SENDING';
export const MESSAGES_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_SENT = 'MESSAGE_SENT';

export const NICKNAME_CHANGED = 'NICKNAME_CHANGED';
